services:

  influxdb:

    image: influxdb:2

    container_name: influxdb

    ports:

      - "8086:8086"

    volumes:

      - influx_data:/var/lib/influxdb2


  grafana:

    image: grafana/grafana

    container_name: grafana

    ports:

      - "3000:3000"

    volumes:

      - grafana_data:/var/lib/grafana


volumes:

  grafana_data:

    name: weather_demo_grafana_data

  influx_data:

    name: weather_demo_influx_data